@echo off
rem this file has been generated by batchgen and may be overwritten
rem command line: ..\bin\batchgen.exe  whsw.bg
rem date 2016-5-5 17:18:59

@goto main
:main

 rem run bc bert [1"|"2] 3
@echo off

rem while
:WH1
if "%1" == "bert" goto WB1
goto EW1
:WB1
@echo w1
rem switch
rem case
if not "%2" == "1" goto EC0
@echo sw1 c1
rem end case
:EC0
rem case
if not "%2" == "2" goto EC2
@echo sw1 c2
rem while
:WH0
if "%2" == "2" goto WB0
goto EW0
:WB0
@echo w2
rem switch
rem case
if not "%3" == "3" goto EC1
@echo sw3 c3
rem end case
:EC1
rem default
rem end default
:ES0
shift
goto WH0
rem endwhile
:EW0
rem end case
:EC2
rem default
rem end default
:ES1

    shift
   
goto WH1
rem endwhile
:EW1
:batch_end
