batchgen: batchgen.c File Reference
batchgen.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "batchgen.h"
#include "stacks.h"
#include "sr.h"
#include "optim.h"
Functions
char getopts (int argc, char *argv[])
void set_flag (char *argv)
void make_banner (char *progname, char *fname, char *opts, char banner[BUFSIZ])
void make_opts (char opts[BUFSIZ])
int write_code (char *banner, FILE *uoofp)
int write_optim_code (char *banner, char **ca, FILE *oofp)
int main (int argc, char *argv[])
Variables
FILE * yyin = (FILE *) 0
int yydebug
char optflag = 0
code_list_t * cl = NULL
Function Documentation
char getopts (int argc, char * argv[])
Definition at line 98 of file batchgen.c.
References set_flag().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 29 of file batchgen.c.
References add_string(), code_join(), getopts(), make_banner(), make_opts(), new_code_node(), num_sr, optflag, srcode, stack_init(), TMPFNAM, write_code(), write_optim_code(), yydebug, yyin, and yyparse().
void make_banner (char * progname, char * fname, char * opts, char banner[BUFSIZ])
Definition at line 168 of file batchgen.c.
Referenced by main().
void make_opts (char opts[BUFSIZ])
Definition at line 157 of file batchgen.c.
References optflag, remove_blanks, and remove_rems.
Referenced by main().
void set_flag (char * argv)
Definition at line 120 of file batchgen.c.
References optflag, remove_blanks, and remove_rems.
Referenced by getopts().
int write_code (char * banner, FILE * uoofp)
Definition at line 198 of file batchgen.c.
References emit().
Referenced by main().
int write_optim_code (char * banner, char ** ca, FILE * oofp)
Definition at line 214 of file batchgen.c.
References copy_lines(), DUD_FILE_LABEL, emit(), F_optimize(), optimize(), and print_ca().
Referenced by main().
Variable Documentation
code_list_t* cl = NULL
Definition at line 27 of file batchgen.c.
Referenced by yyparse().
char optflag = 0
Definition at line 26 of file batchgen.c.
Referenced by main(), make_opts(), and set_flag().
int yydebug
Definition at line 280 of file y.tab.c.
Referenced by main(), and yyparse().
FILE * yyin = (FILE *) 0
Definition at line 265 of file lex.yy.c.
Referenced by main().