batchgen: batchgen.h File Reference
batchgen.h File Reference
Classes
struct code_list
struct goto_list
struct expr
Defines
#define TEXTLEN 200
#define LAB_PFX "L_"
#define END_CASE_PFX "EC"
#define END_SWITCH_PFX "ES"
#define ENDIF_PFX "EI"
#define ELSE_PFX "LS"
#define IF_PFX "IF"
#define WHILE_PFX "WH"
#define ENDWHILE_PFX "EW"
#define WHILE_BODY_PFX "WB"
#define OR_FALSE_PFX "ORF"
#define AND_TRUE_PFX "AT"
#define SR_PFX "SR"
#define END_SR_PFX "ESR"
#define RET_LABEL "_ret_label"
#define END_LABEL "batch_end"
#define DUD_FILE_LABEL "dud_file"
Typedefs
typedef struct code_list code_list_t
typedef struct goto_list goto_list_t
typedef struct expr expr_t
Functions
int yyparse (void)
int yylex (void)
code_list_t * new_code_node (void)
char add_string (code_list_t *node, char *string)
char add_text (expr_t *node, char *string)
code_list_t * code_join (int n,...)
expr_t * new_expr (void)
code_list_t * make_expr_code (char *text, expr_t *expr)
void emit (code_list_t *c1, FILE *fp)
char concat_text (expr_t *n1, expr_t *n2)
Variables
char optflag
code_list_t * cl
Define Documentation
#define AND_TRUE_PFX "AT"
Definition at line 39 of file batchgen.h.
Referenced by yyparse().
#define DUD_FILE_LABEL "dud_file"
Definition at line 45 of file batchgen.h.
Referenced by write_optim_code().
#define ELSE_PFX "LS"
Definition at line 33 of file batchgen.h.
Referenced by yyparse().
#define END_CASE_PFX "EC"
Definition at line 30 of file batchgen.h.
Referenced by yyparse().
#define END_LABEL "batch_end"
Definition at line 44 of file batchgen.h.
Referenced by yyparse().
#define END_SR_PFX "ESR"
Definition at line 41 of file batchgen.h.
Referenced by F_get_labels(), and is_esr().
#define END_SWITCH_PFX "ES"
Definition at line 31 of file batchgen.h.
Referenced by yyparse().
#define ENDIF_PFX "EI"
Definition at line 32 of file batchgen.h.
Referenced by yyparse().
#define ENDWHILE_PFX "EW"
Definition at line 36 of file batchgen.h.
Referenced by yyparse().
#define IF_PFX "IF"
Definition at line 34 of file batchgen.h.
Referenced by yyparse().
#define LAB_PFX "L_"
Definition at line 29 of file batchgen.h.
#define OR_FALSE_PFX "ORF"
Definition at line 38 of file batchgen.h.
Referenced by yyparse().
#define RET_LABEL "_ret_label"
Definition at line 43 of file batchgen.h.
Referenced by F_get_labels().
#define SR_PFX "SR"
Definition at line 40 of file batchgen.h.
#define TEXTLEN 200
Definition at line 28 of file batchgen.h.
Referenced by concat_text(), copy_lines(), F_del_line(), F_del_unrefd_labs(), F_get_labels(), F_line_count(), F_remove_blanks(), F_remove_rems(), and F_reref_labs().
#define WHILE_BODY_PFX "WB"
Definition at line 37 of file batchgen.h.
Referenced by yyparse().
#define WHILE_PFX "WH"
Definition at line 35 of file batchgen.h.
Referenced by yyparse().
Typedef Documentation
typedef struct code_list code_list_t
Definition at line 8 of file batchgen.h.
typedef struct expr expr_t
Definition at line 26 of file batchgen.h.
typedef struct goto_list goto_list_t
Definition at line 16 of file batchgen.h.
Function Documentation
char add_string (code_list_t * node, char * string)
Definition at line 309 of file y.tab.c.
References code_list::code.
Referenced by add_srcode(), add_text(), main(), make_expr_code(), and yyparse().
char add_text (expr_t * node, char * string)
Definition at line 319 of file y.tab.c.
References add_string(), expr::expr_code, and new_code_node().
Referenced by concat_text(), make_expr_code(), and yyparse().
code_list_t* code_join (int n, ...)
Definition at line 350 of file y.tab.c.
References code_list::next.
Referenced by add_srcode(), main(), make_expr_code(), and yyparse().
char concat_text (expr_t * n1, expr_t * n2)
Definition at line 329 of file y.tab.c.
References add_text(), code_list::code, expr::expr_code, and TEXTLEN.
Referenced by yyparse().
void emit (code_list_t * c1, FILE * fp)
Definition at line 375 of file y.tab.c.
References code_list::code, and code_list::next.
Referenced by write_code(), and write_optim_code().
code_list_t* make_expr_code (char * text, expr_t * expr)
Definition at line 384 of file y.tab.c.
References add_string(), add_text(), code_join(), expr::expr_code, expr::falselist, makelist(), new_code_node(), and expr::truelist.
Referenced by yyparse().
code_list_t* new_code_node (void)
Definition at line 299 of file y.tab.c.
Referenced by add_srcode(), add_text(), main(), make_expr_code(), and yyparse().
expr_t* new_expr (void)
Definition at line 304 of file y.tab.c.
Referenced by yyparse().
int yylex (void)
Definition at line 610 of file lex.yy.c.
References BEGIN, dos_cmd, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, INITIAL, is_func(), YY_BREAK, YY_BUF_SIZE, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_c_buf_p, yy_buffer_state::yy_ch_buf, yy_create_buffer(), yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yy_hold_char, yy_init, yy_buffer_state::yy_input_file, yy_load_buffer_state(), yy_buffer_state::yy_n_chars, yy_n_chars, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yyleng, yyless, yyout, yyterminate, yytext_ptr, and yywrap().
Referenced by yyparse().
int yyparse (void)
Definition at line 436 of file y.tab.c.
References add_srcode(), add_string(), add_text(), AND_TRUE_PFX, backpatch_str(), cl, code_list::code, code_join(), YYSTYPE::code_node, concat_text(), ELSE_PFX, END_CASE_PFX, END_LABEL, END_SWITCH_PFX, ENDIF_PFX, ENDWHILE_PFX, expr::expr_code, YYSTYPE::expr_node, expr::falselist, find_func(), code_list::gotos, IF_PFX, in_sr, install_func(), inswitch(), YYSTYPE::integer, inwhile(), is_func(), label_details::label, lineno, make_expr_code(), makelist(), merge(), new_code_node(), new_expr(), newcaselabel, newcondlabel, newiflabel, newlabel, newwhilelabel, code_list::next, OR_FALSE_PFX, spop(), spush(), sr_call_count, to_ss(), to_ws(), top_cur_stk(), expr::truelist, WHILE_BODY_PFX, WHILE_PFX, wpop(), wpush(), yychar, yycheck, yydebug, yydefred, yydgoto, YYERRCODE, yyerrflag, yyerror(), YYFINAL, yygindex, yylen, yylex(), yylhs, YYMAXTOKEN, yynerrs, YYPREFIX, yyrindex, yysindex, yyss, yyssp, yystacksize, yytable, YYTABLESIZE, and yytext.
Referenced by main().
Variable Documentation
code_list_t* cl
Definition at line 27 of file batchgen.c.
Referenced by yyparse().
char optflag
Definition at line 26 of file batchgen.c.
Referenced by main(), make_opts(), and set_flag().