batchgen: bkpatch.c File Reference
bkpatch.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "batchgen.h"
#include "bkpatch.h"
Functions
goto_list_t * makelist (code_list_t *goto_node)
goto_list_t * merge (goto_list_t *l1, goto_list_t *l2)
void backpatch (goto_list_t *goto_list, int label)
void backpatch_str (goto_list_t *goto_list, char *label)
Function Documentation
void backpatch (goto_list_t * goto_list, int label)
Definition at line 39 of file bkpatch.c.
References goto_list::labelptr, and goto_list::next.
void backpatch_str (goto_list_t * goto_list, char * label)
Definition at line 59 of file bkpatch.c.
References goto_list::labelptr, and goto_list::next.
Referenced by yyparse().
goto_list_t* makelist (code_list_t * goto_node)
Definition at line 9 of file bkpatch.c.
References code_list::code, goto_list::labelptr, and goto_list::next.
Referenced by make_expr_code(), and yyparse().
goto_list_t* merge (goto_list_t * l1, goto_list_t * l2)
Definition at line 27 of file bkpatch.c.
References goto_list::next.
Referenced by yyparse().