batchgen: foptim.h File Reference
foptim.h File Reference
Classes
struct label_details
Defines
#define PEEPSZ 3
#define TMPFNAM "bgo.tmp"
Typedefs
typedef struct label_details label_detail_t
Functions
char ** copy_lines (code_list_t *code)
int list_line_count (code_list_t *cl)
char next_char (void)
char install_def (char *str)
char install_ref (char *str)
int find_label (char *str)
char del_unrefd_labs (char *name, char **ca)
void print_ca (char **ca, FILE *fp)
char * find_word (char *str, char *word)
char is_branch (char *str)
char is_uncond_br (char *str)
char is_label (char *str)
char * get_label_ref (char *str)
char * get_label_def (char *str)
char negate (char *str)
char is_cond_br (char *str)
char is_rem (char *str)
char is_blank (char *str)
char check_labels (void)
int cn_count (code_list_t *code)
char is_esr (char *lab)
char F_optimize (void)
char F_get_labels (void)
void F_del_line (int line_no)
char F_reref_labs (char *newlab, char *oldlab)
int F_remove_blanks (void)
int F_remove_rems (void)
int F_line_count (char *fname)
char F_del_unrefd_labs (char *name)
char next_peep (char peep[PEEPSZ][TEXTLEN], int *end_of_file_head)
char dead_code (int i, int valid_lines, int page)
char redund_goto (int i)
char jump_over_jump (int i)
char lablabjmpjmp (int i)
Variables
char remove_rems
char remove_blanks
Define Documentation
#define PEEPSZ 3
Definition at line 1 of file foptim.h.
#define TMPFNAM "bgo.tmp"
Definition at line 2 of file foptim.h.
Referenced by F_del_line(), F_del_unrefd_labs(), F_get_labels(), F_remove_blanks(), F_remove_rems(), F_reref_labs(), and main().
Typedef Documentation
typedef struct label_details label_detail_t
Definition at line 11 of file foptim.h.
Function Documentation
char check_labels (void)
Definition at line 796 of file foptim.c.
int cn_count (code_list_t * code)
Definition at line 812 of file foptim.c.
char** copy_lines (code_list_t * code)
Definition at line 29 of file optim.c.
Referenced by write_optim_code().
char dead_code (int i, int valid_lines, int page)
Definition at line 832 of file foptim.c.
References is_label().
Referenced by F_optimize().
char del_unrefd_labs (char * name, char ** ca)
Definition at line 572 of file optim.c.
Referenced by optimize().
void F_del_line (int line_no)
Definition at line 670 of file foptim.c.
References TEXTLEN, and TMPFNAM.
char F_del_unrefd_labs (char * name)
Definition at line 534 of file foptim.c.
References is_label(), TEXTLEN, and TMPFNAM.
Referenced by F_optimize().
char F_get_labels (void)
Definition at line 148 of file foptim.c.
References END_SR_PFX, install_def(), install_ref(), is_branch(), is_label(), RET_LABEL, sr_call_count, TEXTLEN, and TMPFNAM.
Referenced by F_optimize().
int F_line_count (char * fname)
Definition at line 334 of file foptim.c.
References TEXTLEN.
Referenced by F_optimize().
char F_optimize (void)
Definition at line 414 of file foptim.c.
References check_labels(), dead_code(), F_del_unrefd_labs(), F_get_labels(), F_line_count(), F_remove_blanks(), F_remove_rems(), is_cond_br(), is_label(), is_uncond_br(), jump_over_jump(), lablabjmpjmp(), num_labels, redund_goto(), remove_blanks, and remove_rems.
Referenced by write_optim_code().
int F_remove_blanks (void)
Definition at line 306 of file foptim.c.
References is_blank(), TEXTLEN, and TMPFNAM.
Referenced by F_optimize().
int F_remove_rems (void)
Definition at line 353 of file foptim.c.
References is_rem(), TEXTLEN, and TMPFNAM.
Referenced by F_optimize().
char F_reref_labs (char * newlab, char * oldlab)
Definition at line 750 of file foptim.c.
References find_label(), find_word(), is_branch(), TEXTLEN, and TMPFNAM.
Referenced by lablabjmpjmp().
int find_label (char * str)
Definition at line 293 of file foptim.c.
char* find_word (char * str, char * word)
Definition at line 580 of file foptim.c.
char* get_label_def (char * str)
Definition at line 701 of file foptim.c.
char* get_label_ref (char * str)
Definition at line 713 of file foptim.c.
char install_def (char * str)
Definition at line 206 of file foptim.c.
char install_ref (char * str)
Definition at line 248 of file foptim.c.
char is_blank (char * str)
Definition at line 634 of file foptim.c.
char is_branch (char * str)
Definition at line 610 of file foptim.c.
char is_cond_br (char * str)
Definition at line 652 of file foptim.c.
char is_esr (char * lab)
Definition at line 825 of file foptim.c.
char is_label (char * str)
Definition at line 660 of file foptim.c.
char is_rem (char * str)
Definition at line 624 of file foptim.c.
char is_uncond_br (char * str)
Definition at line 644 of file foptim.c.
char jump_over_jump (int i)
Definition at line 867 of file foptim.c.
References get_label_def(), get_label_ref(), is_label(), and negate().
Referenced by F_optimize().
char lablabjmpjmp (int i)
Definition at line 897 of file foptim.c.
References F_reref_labs(), get_label_def(), get_label_ref(), is_esr(), is_label(), and is_uncond_br().
Referenced by F_optimize().
int list_line_count (code_list_t * cl)
Definition at line 30 of file foptim.c.
char negate (char * str)
Definition at line 725 of file foptim.c.
Referenced by jump_over_jump(), and optimize_line().
char next_char (void)
Definition at line 49 of file foptim.c.
char next_peep (char peep[PEEPSZ][TEXTLEN], int * end_of_file_head)
Definition at line 381 of file foptim.c.
void print_ca (char ** ca, FILE * fp)
Definition at line 568 of file foptim.c.
char redund_goto (int i)
Definition at line 852 of file foptim.c.
References get_label_def(), and get_label_ref().
Referenced by F_optimize().
Variable Documentation
char remove_blanks
Definition at line 21 of file foptim.c.
char remove_rems
Definition at line 20 of file foptim.c.