batchgen: lex.yy.c File Reference
lex.yy.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>
#include <string.h>
#include "batchgen.h"
#include "y.tab.h"
#include "sr.h"
Classes
struct yy_buffer_state
Defines
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define yyconst
#define YY_PROTO(proto) ()
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define BEGIN yy_start = 1 + 2 *
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE yyrestart(yyin)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define yyless(n)
#define unput(c) yyunput(c, yytext_ptr)
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER yy_current_buffer
#define YY_FLUSH_BUFFER yy_flush_buffer(yy_current_buffer)
#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)
#define yytext_ptr yytext
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define INITIAL 0
#define YY_USE_PROTOS
#define dos_cmd 1
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#define YY_READ_BUF_SIZE 8192
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#define YY_DECL int yylex YY_PROTO((void))
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
Typedefs
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef unsigned int yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void yyrestart ()
void yy_switch_to_buffer ()
void yy_load_buffer_state ()
YY_BUFFER_STATE yy_create_buffer ()
void yy_delete_buffer ()
void yy_init_buffer ()
void yy_flush_buffer ()
YY_BUFFER_STATE yy_scan_buffer ()
YY_BUFFER_STATE yy_scan_string ()
YY_BUFFER_STATE yy_scan_bytes ()
static void * yy_flex_alloc ()
static void * yy_flex_realloc ()
static void yy_flex_free ()
static yy_state_type yy_get_previous_state ()
static yy_state_type yy_try_NUL_trans ()
static int yy_get_next_buffer ()
static void yy_fatal_error ()
int yywrap ()
static void yyunput ()
static int input ()
int yylex ()
static yy_state_type yy_try_NUL_trans (yy_state_type yy_current_state)
static void yyunput (int c, register char *yy_bp)
void yyrestart (FILE *input_file)
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
YY_BUFFER_STATE yy_create_buffer (FILE *file, int size)
void yy_delete_buffer (YY_BUFFER_STATE b)
int isatty ()
void yy_init_buffer (YY_BUFFER_STATE b, FILE *file)
void yy_flush_buffer (YY_BUFFER_STATE b)
YY_BUFFER_STATE yy_scan_buffer (char *base, yy_size_t size)
YY_BUFFER_STATE yy_scan_string (char *yy_str)
YY_BUFFER_STATE yy_scan_bytes (char *bytes, int len)
static void yy_fatal_error (char msg[])
static void * yy_flex_alloc (yy_size_t size)
static void * yy_flex_realloc (void *ptr, yy_size_t size)
static void yy_flex_free (void *ptr)
Variables
int yyleng
FILE * yyin = (FILE *) 0
FILE * yyout = (FILE *) 0
static YY_BUFFER_STATE yy_current_buffer = 0
static char yy_hold_char
static int yy_n_chars
static char * yy_c_buf_p = (char *) 0
static int yy_init = 1
static int yy_start = 0
static int yy_did_buffer_switch_on_eof
char * yytext
static short int yy_accept [110]
static int yy_ec [256]
static int yy_meta [48]
static short int yy_base [115]
static short int yy_def [115]
static short int yy_nxt [193]
static short int yy_chk [193]
static yy_state_type yy_last_accepting_state
static char * yy_last_accepting_cpos
int lineno
Define Documentation
#define BEGIN yy_start = 1 + 2 *
Definition at line 79 of file lex.yy.c.
Referenced by yylex().
#define dos_cmd 1
Definition at line 463 of file lex.yy.c.
Referenced by yylex().
#define ECHO (void) fwrite(yytext, yyleng, 1, yyout)
Definition at line 545 of file lex.yy.c.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 104 of file lex.yy.c.
Referenced by input(), and yylex().
#define EOB_ACT_END_OF_FILE 1
Definition at line 105 of file lex.yy.c.
Referenced by input(), and yylex().
#define EOB_ACT_LAST_MATCH 2
Definition at line 106 of file lex.yy.c.
Referenced by input(), and yylex().
#define FLEX_SCANNER
Definition at line 7 of file lex.yy.c.
#define INITIAL 0
Definition at line 442 of file lex.yy.c.
Referenced by yylex().
#define REJECT reject_used_but_not_detected
Definition at line 436 of file lex.yy.c.
#define unput (c) yyunput(c, yytext_ptr)
Definition at line 135 of file lex.yy.c.
#define YY_AT_BOL () (yy_current_buffer->yy_at_bol)
Definition at line 262 of file lex.yy.c.
#define YY_BREAK break;
Definition at line 604 of file lex.yy.c.
Referenced by yylex().
#define YY_BUF_SIZE 16384
Definition at line 97 of file lex.yy.c.
Referenced by yylex(), and yyrestart().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 198 of file lex.yy.c.
Referenced by yy_get_next_buffer().
#define YY_BUFFER_NEW 0
Definition at line 186 of file lex.yy.c.
Referenced by yylex().
#define YY_BUFFER_NORMAL 1
Definition at line 187 of file lex.yy.c.
#define YY_CURRENT_BUFFER yy_current_buffer
Definition at line 207 of file lex.yy.c.
#define YY_DECL int yylex YY_PROTO((void))
Definition at line 592 of file lex.yy.c.
#define YY_DO_BEFORE_ACTION
Value:
yytext_ptr = yy_bp; \
        yyleng = (int) (yy_cp - yy_bp); \
        yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
        yy_c_buf_p = yy_cp;
Definition at line 278 of file lex.yy.c.
#define YY_END_OF_BUFFER 31
Definition at line 286 of file lex.yy.c.
Referenced by yylex().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 94 of file lex.yy.c.
Referenced by input(), and yy_scan_buffer().
#define YY_EXIT_FAILURE 2
Definition at line 1661 of file lex.yy.c.
Referenced by yy_fatal_error().
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg)
Definition at line 585 of file lex.yy.c.
Referenced by yy_create_buffer(), yy_get_next_buffer(), yy_scan_buffer(), yy_scan_bytes(), yylex(), and yyunput().
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 8 of file lex.yy.c.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 9 of file lex.yy.c.
#define YY_FLUSH_BUFFER yy_flush_buffer(yy_current_buffer)
Definition at line 236 of file lex.yy.c.
#define YY_INPUT (buf, result, max_size)
Value:
if (yy_current_buffer->yy_is_interactive) \
                { \
                int c = '*', n; \
                for ( n = 0; n < max_size && \
                             (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
                        buf[n] = (char) c; \
                if ( c == '\n' ) \
                        buf[n++] = (char) c; \
                if ( c == EOF && ferror( yyin ) ) \
                        YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
                  && ferror( yyin ) ) \
                YY_FATAL_ERROR( "input in flex scanner failed" );
Definition at line 552 of file lex.yy.c.
Referenced by yy_get_next_buffer().
#define YY_MORE_ADJ 0
Definition at line 438 of file lex.yy.c.
Referenced by yy_get_next_buffer(), and yy_get_previous_state().
#define yy_new_buffer yy_create_buffer
Definition at line 246 of file lex.yy.c.
#define YY_NEW_FILE yyrestart(yyin)
Definition at line 92 of file lex.yy.c.
#define YY_NO_POP_STATE 1
Definition at line 515 of file lex.yy.c.
#define YY_NO_PUSH_STATE 1
Definition at line 514 of file lex.yy.c.
#define YY_NO_TOP_STATE 1
Definition at line 516 of file lex.yy.c.
#define YY_NULL 0
Definition at line 66 of file lex.yy.c.
#define YY_NUM_RULES 30
Definition at line 285 of file lex.yy.c.
#define YY_PROTO (proto) ()
Definition at line 62 of file lex.yy.c.
#define YY_READ_BUF_SIZE 8192
Definition at line 536 of file lex.yy.c.
Referenced by yy_get_next_buffer().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 439 of file lex.yy.c.
Referenced by yylex().
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 607 of file lex.yy.c.
Referenced by yylex().
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 73 of file lex.yy.c.
Referenced by yy_get_previous_state(), and yylex().
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! yy_current_buffer ) \
                yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_at_bol = at_bol; \
        }
Definition at line 255 of file lex.yy.c.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! yy_current_buffer ) \
                yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
        yy_current_buffer->yy_is_interactive = is_interactive; \
        }
Definition at line 248 of file lex.yy.c.
#define YY_START ((yy_start - 1) / 2)
Definition at line 85 of file lex.yy.c.
Referenced by yylex().
#define YY_START_STACK_INCR 25
Definition at line 580 of file lex.yy.c.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 89 of file lex.yy.c.
Referenced by yylex().
#define YY_USE_PROTOS
Definition at line 444 of file lex.yy.c.
#define YY_USER_ACTION
Definition at line 599 of file lex.yy.c.
#define yyconst
Definition at line 55 of file lex.yy.c.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
                yytext[yyleng] = yy_hold_char; \
                yy_c_buf_p = yytext + n; \
                yy_hold_char = *yy_c_buf_p; \
                *yy_c_buf_p = '\0'; \
                yyleng = n; \
                } \
        while ( 0 )
Definition at line 1680 of file lex.yy.c.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
                *yy_cp = yy_hold_char; \
                YY_RESTORE_YY_MORE_OFFSET \
                yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
Definition at line 1680 of file lex.yy.c.
Referenced by yylex().
#define yymore () yymore_used_but_not_detected
Definition at line 437 of file lex.yy.c.
#define YYSTATE YY_START
Definition at line 86 of file lex.yy.c.
#define yyterminate () return YY_NULL
Definition at line 575 of file lex.yy.c.
Referenced by yylex().
#define yytext_ptr yytext
Definition at line 268 of file lex.yy.c.
Referenced by yy_get_next_buffer(), yy_get_previous_state(), yy_load_buffer_state(), yylex(), and yyunput().
Typedef Documentation
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 99 of file lex.yy.c.
typedef unsigned char YY_CHAR
Definition at line 264 of file lex.yy.c.
typedef unsigned int yy_size_t
Definition at line 141 of file lex.yy.c.
typedef int yy_state_type
Definition at line 266 of file lex.yy.c.
Function Documentation
static int input () [static]
Definition at line 1272 of file lex.yy.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_c_buf_p, yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yy_hold_char, yy_n_chars, yyrestart(), and yywrap().
int isatty ()
Referenced by yy_init_buffer().
YY_BUFFER_STATE yy_create_buffer ()
Referenced by yylex(), and yyrestart().
YY_BUFFER_STATE yy_create_buffer (FILE * file, int size)
Definition at line 1401 of file lex.yy.c.
References yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_flex_alloc(), yy_init_buffer(), and yy_buffer_state::yy_is_our_buffer.
void yy_delete_buffer ()
void yy_delete_buffer (YY_BUFFER_STATE b)
Definition at line 1432 of file lex.yy.c.
References yy_flex_free().
static void yy_fatal_error () [static]
static void yy_fatal_error (char msg[]) [static]
Definition at line 1665 of file lex.yy.c.
References YY_EXIT_FAILURE.
static void* yy_flex_alloc (yy_size_t size) [static]
Definition at line 1729 of file lex.yy.c.
static void* yy_flex_alloc () [static]
Referenced by yy_create_buffer(), yy_scan_buffer(), and yy_scan_bytes().
static void yy_flex_free (void * ptr) [static]
Definition at line 1757 of file lex.yy.c.
static void yy_flex_free () [static]
Referenced by yy_delete_buffer().
static void* yy_flex_realloc (void * ptr, yy_size_t size) [static]
Definition at line 1739 of file lex.yy.c.
static void* yy_flex_realloc () [static]
Referenced by yy_get_next_buffer().
void yy_flush_buffer ()
Referenced by yy_init_buffer().
void yy_flush_buffer (YY_BUFFER_STATE b)
Definition at line 1485 of file lex.yy.c.
References yy_load_buffer_state(), and yy_buffer_state::yy_n_chars.
static int yy_get_next_buffer () [static]
Definition at line 1029 of file lex.yy.c.
References yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yy_buffer_state::yy_buffer_status, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_flex_realloc(), YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yy_buffer_state::yy_n_chars, yy_n_chars, YY_READ_BUF_SIZE, yyrestart(), and yytext_ptr.
Referenced by input(), and yylex().
static yy_state_type yy_get_previous_state () [static]
Definition at line 1161 of file lex.yy.c.
References yy_c_buf_p, YY_MORE_ADJ, YY_SC_TO_UI, yy_start, and yytext_ptr.
Referenced by yylex().
void yy_init_buffer ()
Referenced by yy_create_buffer(), and yyrestart().
void yy_init_buffer (YY_BUFFER_STATE b, FILE * file)
Definition at line 1458 of file lex.yy.c.
References isatty(), and yy_flush_buffer().
void yy_load_buffer_state (void)
Definition at line 1388 of file lex.yy.c.
References yy_buffer_state::yy_buf_pos, yy_c_buf_p, yy_hold_char, yy_buffer_state::yy_input_file, yy_buffer_state::yy_n_chars, yy_n_chars, and yytext_ptr.
Referenced by yy_flush_buffer(), yy_switch_to_buffer(), yylex(), and yyrestart().
YY_BUFFER_STATE yy_scan_buffer ()
Referenced by yy_scan_bytes().
YY_BUFFER_STATE yy_scan_buffer (char * base, yy_size_t size)
Definition at line 1516 of file lex.yy.c.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_flex_alloc(), yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars, and yy_switch_to_buffer().
YY_BUFFER_STATE yy_scan_bytes (char * bytes, int len)
Definition at line 1571 of file lex.yy.c.
References YY_FATAL_ERROR, yy_flex_alloc(), yy_buffer_state::yy_is_our_buffer, and yy_scan_buffer().
YY_BUFFER_STATE yy_scan_bytes ()
Referenced by yy_scan_string().
YY_BUFFER_STATE yy_scan_string ()
YY_BUFFER_STATE yy_scan_string (char * yy_str)
Definition at line 1554 of file lex.yy.c.
References yy_scan_bytes().
void yy_switch_to_buffer ()
Referenced by yy_scan_buffer().
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
Definition at line 1358 of file lex.yy.c.
References yy_buffer_state::yy_buf_pos, yy_c_buf_p, yy_did_buffer_switch_on_eof, yy_hold_char, yy_load_buffer_state(), yy_n_chars, and yy_buffer_state::yy_n_chars.
static yy_state_type yy_try_NUL_trans () [static]
Referenced by yylex().
static yy_state_type yy_try_NUL_trans (yy_state_type yy_current_state) [static]
Definition at line 1196 of file lex.yy.c.
References yy_c_buf_p.
int yylex (void)
Definition at line 610 of file lex.yy.c.
References BEGIN, dos_cmd, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, INITIAL, is_func(), YY_BREAK, YY_BUF_SIZE, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_c_buf_p, yy_buffer_state::yy_ch_buf, yy_create_buffer(), yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yy_hold_char, yy_init, yy_buffer_state::yy_input_file, yy_load_buffer_state(), yy_buffer_state::yy_n_chars, yy_n_chars, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yyleng, yyless, yyout, yyterminate, yytext_ptr, and yywrap().
Referenced by yyparse().
void yyrestart ()
Referenced by input(), and yy_get_next_buffer().
void yyrestart (FILE * input_file)
Definition at line 1343 of file lex.yy.c.
References YY_BUF_SIZE, yy_create_buffer(), yy_init_buffer(), and yy_load_buffer_state().
static void yyunput () [static]
static void yyunput (int c, register char * yy_bp) [static]
Definition at line 1226 of file lex.yy.c.
References yy_buffer_state::yy_buf_size, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_hold_char, yy_buffer_state::yy_n_chars, yy_n_chars, and yytext_ptr.
int yywrap (void)
Definition at line 1777 of file lex.yy.c.
Referenced by input(), and yylex().
Variable Documentation
int lineno
Definition at line 29 of file y.tab.c.
Referenced by yyparse().
short int yy_accept[110] [static]
Initial value:
    {   0,
        0,    0,    5,    5,   31,   29,    1,    2,   29,   29,
       29,   29,   29,   28,   27,   29,   29,   28,   29,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   29,    5,
        5,    1,   18,   22,    3,    0,   20,   16,   28,   27,
       17,   19,   28,   28,    4,   28,   28,   28,   28,   28,
       28,   28,    6,   28,   28,   28,   15,    5,    3,    0,
       21,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,    7,   28,    8,   28,
       28,   14,   28,   28,   28,   28,   26,   13,   28,   28,
       25,   28,   28,   11,   28,   28,   28,   12,    9,   28,
       10,   28,   28,   28,   28,   28,   24,   23,    0
    }
Definition at line 287 of file lex.yy.c.
short int yy_base[115] [static]
Initial value:
    {   0,
        0,    0,  138,  137,  142,  145,  139,  145,  127,  134,
      111,  125,  127,    0,  123,  121,  120,   28,  126,   91,
      102,   97,   13,   97,   94,   94,   80,   90,   76,    0,
       95,  119,  145,  145,  145,  112,  111,  145,    0,  106,
      145,  145,   97,   99,  145,   83,   73,   80,   71,   71,
       75,   77,    0,   66,   72,   71,  145,    0,    0,   97,
      145,   85,   82,   74,   69,   72,   67,   59,   56,   63,
       52,   52,   56,   72,   69,   54,    0,   46,    0,   48,
       45,    0,   46,   55,   52,   65,    0,    0,   45,   44,
        0,   42,   44,    0,   53,   26,   26,    0,    0,   34,
        0,   12,   39,   22,   33,   12,    0,    0,  145,   59,
       61,   65,   70,   74
    }
Definition at line 344 of file lex.yy.c.
char* yy_c_buf_p = (char *) 0 [static]
Definition at line 219 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), yy_get_previous_state(), yy_load_buffer_state(), yy_switch_to_buffer(), yy_try_NUL_trans(), yylex(), and yyunput().
short int yy_chk[193] [static]
Initial value:
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   18,  106,   23,
      105,   18,   23,  104,  103,  102,  100,   97,   23,  110,
      110,  110,  110,  110,  111,  111,  112,   96,   95,  112,
      113,  113,  113,  113,  113,  114,  114,   93,  114,   92,
       90,   89,   86,   85,   84,   83,   81,   80,   78,   76,
       75,   74,   73,   72,   71,   70,   69,   68,   67,   66,
       65,   64,   63,   62,   60,   56,   55,   54,   52,   51,
       50,   49,   48,   47,   46,   44,   43,   40,   37,   36,
       32,   31,   29,   28,   27,   26,   25,   24,   22,   21,
       20,   19,   17,   16,   15,   13,   12,   11,   10,    9,
        7,    5,    4,    3,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109
    }
Definition at line 404 of file lex.yy.c.
YY_BUFFER_STATE yy_current_buffer = 0 [static]
Definition at line 201 of file lex.yy.c.
short int yy_def[115] [static]
Initial value:
    {   0,
      109,    1,  110,  110,  109,  109,  109,  109,  109,  109,
      109,  111,  109,  112,  112,  109,  109,  112,  109,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  109,  113,
      113,  109,  109,  109,  109,  114,  114,  109,  112,  112,
      109,  109,  112,  112,  109,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  109,  113,  113,  114,
      109,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,    0,  109,
      109,  109,  109,  109
    }
Definition at line 361 of file lex.yy.c.
int yy_did_buffer_switch_on_eof [static]
Definition at line 226 of file lex.yy.c.
Referenced by input(), yy_switch_to_buffer(), and yylex().
int yy_ec[256] [static]
Definition at line 303 of file lex.yy.c.
char yy_hold_char [static]
Definition at line 211 of file lex.yy.c.
Referenced by input(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex(), and yyunput().
int yy_init = 1 [static]
Definition at line 220 of file lex.yy.c.
Referenced by yylex().
char* yy_last_accepting_cpos [static]
Definition at line 431 of file lex.yy.c.
yy_state_type yy_last_accepting_state [static]
Definition at line 430 of file lex.yy.c.
int yy_meta[48] [static]
Initial value:
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    1,    4,
        5,    5,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    5,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1
    }
Definition at line 335 of file lex.yy.c.
int yy_n_chars [static]
Definition at line 213 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex(), and yyunput().
short int yy_nxt[193] [static]
Initial value:
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       14,   15,   16,   17,   14,   18,   14,   14,   14,   14,
       14,   14,   14,   14,   19,   14,    6,   14,   20,   21,
       22,   23,   24,   14,   25,   14,   14,   14,   14,   26,
       27,   14,   14,   14,   28,   14,   29,   43,  108,   49,
      107,   44,   50,  106,  105,  104,  103,  102,   51,   30,
       30,   30,   30,   30,   36,   36,   39,  101,  100,   39,
       58,   58,   58,   58,   58,   60,   60,   99,   60,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   89,   88,
       87,   86,   85,   84,   83,   82,   81,   80,   79,   78,
       77,   76,   75,   74,   61,   73,   72,   71,   70,   69,
       68,   67,   66,   65,   64,   63,   62,   40,   61,   61,
       32,   59,   57,   56,   55,   54,   53,   52,   48,   47,
       46,   45,   42,   41,   40,   38,   37,   35,   34,   33,
       32,  109,   31,   31,    5,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109
    }
Definition at line 378 of file lex.yy.c.
int yy_start = 0 [static]
Definition at line 221 of file lex.yy.c.
Referenced by yy_get_previous_state(), and yylex().
FILE* yyin = (FILE *) 0
Definition at line 265 of file lex.yy.c.
int yyleng
Definition at line 216 of file lex.yy.c.
Referenced by yylex().
FILE * yyout = (FILE *) 0
Definition at line 265 of file lex.yy.c.
Referenced by yylex().
char * yytext
Definition at line 440 of file lex.yy.c.
Referenced by yyparse().