batchgen: optim.h File Reference
optim.h File Reference
Classes
struct label_details
Defines
#define PEEPSZ 5
#define TMPFNAM "bgo.tmp"
Typedefs
typedef struct label_details label_detail_t
Functions
char ** copy_lines (code_list_t *code)
int list_line_count (code_list_t *cl)
char next_char (void)
char optimize (char **ca)
char optimize_line (char **ca, int lin)
char get_labels (char **ca)
char install_def (char *str)
char install_ref (char *str)
int find_label (char *str)
char del_unrefd_labs (char *name, char **ca)
void print_ca (char **ca, FILE *fp)
char * find_word (char *str, char *word)
char is_branch (char *str)
char is_call (char *str)
char is_uncond_br (char *str)
char is_label (char *str)
void del_line (char **ca, int line_no)
char * get_label_ref (char *str)
char * get_label_def (char *str)
char negate (char **str)
char is_cond_br (char *str)
char is_rem (char *str)
char is_blank (char *str)
char reref_labs (char **ca, char *newlab, char *oldlab)
char check_labels (void)
int cn_count (code_list_t *code)
char is_esr (char *lab)
Variables
char remove_rems
char remove_blanks
Define Documentation
#define PEEPSZ 5
Definition at line 1 of file optim.h.
#define TMPFNAM "bgo.tmp"
Definition at line 2 of file optim.h.
Typedef Documentation
typedef struct label_details label_detail_t
Definition at line 11 of file optim.h.
Function Documentation
char check_labels (void)
Definition at line 796 of file foptim.c.
References max_labels.
Referenced by F_optimize(), and optimize().
int cn_count (code_list_t * code)
Definition at line 812 of file foptim.c.
References code_list::next.
Referenced by copy_lines().
char** copy_lines (code_list_t * code)
Definition at line 29 of file optim.c.
References cn_count(), code_list::code, code_lines, codeptr, END_OF_LIST, list_line_count(), next_char(), strdup(), and TEXTLEN.
void del_line (char ** ca, int line_no)
Definition at line 725 of file optim.c.
Referenced by del_unrefd_labs(), optimize(), and optimize_line().
char del_unrefd_labs (char * name, char ** ca)
Definition at line 572 of file optim.c.
References del_line(), find_word(), and is_label().
int find_label (char * str)
Definition at line 293 of file foptim.c.
References num_labels.
Referenced by F_reref_labs(), install_def(), install_ref(), and reref_labs().
char* find_word (char * str, char * word)
Definition at line 580 of file foptim.c.
Referenced by del_unrefd_labs(), F_reref_labs(), is_branch(), is_call(), is_cond_br(), is_uncond_br(), and reref_labs().
char* get_label_def (char * str)
Definition at line 701 of file foptim.c.
Referenced by jump_over_jump(), lablabjmpjmp(), optimize_line(), and redund_goto().
char* get_label_ref (char * str)
Definition at line 713 of file foptim.c.
Referenced by jump_over_jump(), lablabjmpjmp(), optimize_line(), and redund_goto().
char get_labels (char ** ca)
Definition at line 205 of file optim.c.
References install_def(), install_ref(), is_branch(), is_call(), and is_label().
Referenced by optimize().
char install_def (char * str)
Definition at line 206 of file foptim.c.
References label_details::defd, find_label(), label_details::label, label_incr, max_labels, num_labels, and label_details::refd.
Referenced by F_get_labels(), and get_labels().
char install_ref (char * str)
Definition at line 248 of file foptim.c.
References label_details::defd, find_label(), label_details::label, label_incr, max_labels, num_labels, and label_details::refd.
Referenced by F_get_labels(), and get_labels().
char is_blank (char * str)
Definition at line 634 of file foptim.c.
Referenced by F_remove_blanks(), optimize(), and optimize_line().
char is_branch (char * str)
Definition at line 610 of file foptim.c.
References find_word().
Referenced by F_get_labels(), F_reref_labs(), get_labels(), is_cond_br(), is_uncond_br(), and reref_labs().
char is_call (char * str)
Definition at line 653 of file optim.c.
References find_word().
Referenced by get_labels().
char is_cond_br (char * str)
Definition at line 652 of file foptim.c.
References find_word(), and is_branch().
Referenced by F_optimize(), and optimize_line().
char is_esr (char * lab)
Definition at line 825 of file foptim.c.
References END_SR_PFX.
Referenced by lablabjmpjmp(), and optimize_line().
char is_label (char * str)
Definition at line 660 of file foptim.c.
Referenced by dead_code(), del_unrefd_labs(), F_del_unrefd_labs(), F_get_labels(), F_optimize(), get_labels(), jump_over_jump(), lablabjmpjmp(), and optimize_line().
char is_rem (char * str)
Definition at line 624 of file foptim.c.
Referenced by F_remove_rems(), and optimize().
char is_uncond_br (char * str)
Definition at line 644 of file foptim.c.
References find_word(), and is_branch().
Referenced by F_optimize(), lablabjmpjmp(), and optimize_line().
int list_line_count (code_list_t * cl)
Definition at line 30 of file foptim.c.
References code_list::code, and code_list::next.
Referenced by copy_lines().
char negate (char ** str)
Definition at line 763 of file optim.c.
char next_char (void)
Definition at line 49 of file foptim.c.
References code_list::code, codeptr, and code_list::next.
Referenced by copy_lines().
char optimize (char ** ca)
Definition at line 359 of file optim.c.
References check_labels(), del_line(), del_unrefd_labs(), get_labels(), is_blank(), is_rem(), num_labels, optimize_line(), remove_blanks, and remove_rems.
Referenced by write_optim_code().
char optimize_line (char ** ca, int lin)
Definition at line 435 of file optim.c.
References del_line(), get_label_def(), get_label_ref(), is_blank(), is_cond_br(), is_esr(), is_label(), is_uncond_br(), negate(), remove_blanks, and reref_labs().
Referenced by optimize().
void print_ca (char ** ca, FILE * fp)
Definition at line 568 of file foptim.c.
Referenced by write_optim_code().
char reref_labs (char ** ca, char * newlab, char * oldlab)
Definition at line 788 of file optim.c.
References find_label(), find_word(), and is_branch().
Referenced by optimize_line().
Variable Documentation
char remove_blanks
Definition at line 21 of file foptim.c.
Referenced by F_optimize(), make_opts(), optimize(), optimize_line(), and set_flag().
char remove_rems
Definition at line 20 of file foptim.c.
Referenced by F_optimize(), make_opts(), optimize(), and set_flag().