batchgen: optim.c File Reference
optim.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "batchgen.h"
#include "optim.h"
Defines
#define END_OF_LIST -1
Functions
char ** copy_lines (code_list_t *code)
int list_line_count (code_list_t *cl)
char next_char (void)
char get_labels (char **ca)
char install_def (char *str)
char install_ref (char *str)
int find_label (char *str)
char optimize (char **ca)
char optimize_line (char **ca, int line)
char del_unrefd_labs (char *name, char **ca)
void print_ca (char **ca, FILE *fp)
char * find_word (char *str, char *word)
char is_branch (char *str)
char is_call (char *str)
char is_rem (char *str)
char is_blank (char *str)
char is_uncond_br (char *str)
char is_cond_br (char *str)
char is_label (char *str)
void del_line (char **ca, int line_no)
char * get_label_def (char *str)
char * get_label_ref (char *str)
char negate (char **str)
char reref_labs (char **ca, char *newlab, char *oldlab)
char check_labels (void)
int cn_count (code_list_t *code)
char is_esr (char *lab)
Variables
label_detail_t * labels = NULL
int code_lines
int max_labels = 0
int num_labels = 0
int label_incr = 50
char remove_rems = 0
char remove_blanks = 0
FILE * ofp
static code_list_t * clptr
static char * codeptr
Define Documentation
#define END_OF_LIST -1
Definition at line 13 of file optim.c.
Referenced by copy_lines().
Function Documentation
char check_labels (void)
Definition at line 822 of file optim.c.
References max_labels.
int cn_count (code_list_t * code)
Definition at line 838 of file optim.c.
References code_list::next.
char** copy_lines (code_list_t * code)
Definition at line 29 of file optim.c.
References cn_count(), code_list::code, code_lines, codeptr, END_OF_LIST, list_line_count(), next_char(), strdup(), and TEXTLEN.
Referenced by write_optim_code().
void del_line (char ** ca, int line_no)
Definition at line 725 of file optim.c.
Referenced by del_unrefd_labs(), optimize(), and optimize_line().
char del_unrefd_labs (char * name, char ** ca)
Definition at line 572 of file optim.c.
References del_line(), find_word(), and is_label().
Referenced by optimize().
int find_label (char * str)
Definition at line 346 of file optim.c.
References num_labels.
char* find_word (char * str, char * word)
Definition at line 608 of file optim.c.
char* get_label_def (char * str)
Definition at line 739 of file optim.c.
char* get_label_ref (char * str)
Definition at line 751 of file optim.c.
char get_labels (char ** ca)
Definition at line 205 of file optim.c.
References install_def(), install_ref(), is_branch(), is_call(), and is_label().
Referenced by optimize().
char install_def (char * str)
Definition at line 259 of file optim.c.
References label_details::defd, find_label(), label_details::label, label_incr, max_labels, num_labels, and label_details::refd.
char install_ref (char * str)
Definition at line 301 of file optim.c.
References label_details::defd, find_label(), label_details::label, label_incr, max_labels, num_labels, and label_details::refd.
char is_blank (char * str)
Definition at line 674 of file optim.c.
char is_branch (char * str)
Definition at line 639 of file optim.c.
References find_word().
char is_call (char * str)
Definition at line 653 of file optim.c.
References find_word().
Referenced by get_labels().
char is_cond_br (char * str)
Definition at line 692 of file optim.c.
References find_word(), and is_branch().
char is_esr (char * lab)
Definition at line 851 of file optim.c.
References END_SR_PFX.
char is_label (char * str)
Definition at line 715 of file optim.c.
char is_rem (char * str)
Definition at line 664 of file optim.c.
char is_uncond_br (char * str)
Definition at line 684 of file optim.c.
References find_word(), and is_branch().
int list_line_count (code_list_t * cl)
Definition at line 82 of file optim.c.
References code_list::code, and code_list::next.
char negate (char ** str)
Definition at line 763 of file optim.c.
char next_char (void)
Definition at line 101 of file optim.c.
References code_list::code, codeptr, and code_list::next.
char optimize (char ** ca)
Definition at line 359 of file optim.c.
References check_labels(), del_line(), del_unrefd_labs(), get_labels(), is_blank(), is_rem(), num_labels, optimize_line(), remove_blanks, and remove_rems.
Referenced by write_optim_code().
char optimize_line (char ** ca, int line)
Definition at line 435 of file optim.c.
References del_line(), get_label_def(), get_label_ref(), is_blank(), is_cond_br(), is_esr(), is_label(), is_uncond_br(), negate(), remove_blanks, and reref_labs().
Referenced by optimize().
void print_ca (char ** ca, FILE * fp)
Definition at line 596 of file optim.c.
char reref_labs (char ** ca, char * newlab, char * oldlab)
Definition at line 788 of file optim.c.
References find_label(), find_word(), and is_branch().
Referenced by optimize_line().
Variable Documentation
code_list_t* clptr [static]
Definition at line 26 of file optim.c.
int code_lines
Definition at line 16 of file optim.c.
char* codeptr [static]
Definition at line 27 of file optim.c.
Referenced by copy_lines(), and next_char().
int label_incr = 50
Definition at line 19 of file optim.c.
label_detail_t* labels = NULL
Definition at line 15 of file optim.c.
int max_labels = 0
Definition at line 17 of file optim.c.
int num_labels = 0
Definition at line 18 of file optim.c.
FILE* ofp
char remove_blanks = 0
Definition at line 21 of file optim.c.
char remove_rems = 0
Definition at line 20 of file optim.c.