batchgen: sr.c File Reference
sr.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "batchgen.h"
Functions
char is_func (char *sought)
char * find_func (int func_number)
void install_func (char *name)
char add_srcode (char *name, code_list_t *code)
Variables
int sr_no = 0
int num_sr = 0
char in_sr = 0
int sr_call_count = 0
code_list_t ** srcode = NULL
char ** srnames = NULL
Function Documentation
char add_srcode (char * name, code_list_t * code)
Definition at line 41 of file sr.c.
References add_string(), code_join(), is_func(), new_code_node(), num_sr, and sr_no.
Referenced by yyparse().
char* find_func (int func_number)
Definition at line 25 of file sr.c.
References num_sr, and srnames.
Referenced by yyparse().
void install_func (char * name)
Definition at line 33 of file sr.c.
References num_sr, and srnames.
Referenced by yyparse().
char is_func (char * sought)
Definition at line 15 of file sr.c.
References num_sr, and srnames.
Referenced by add_srcode(), yylex(), and yyparse().
Variable Documentation
char in_sr = 0
Definition at line 10 of file sr.c.
Referenced by yyparse().
int num_sr = 0
Definition at line 9 of file sr.c.
Referenced by add_srcode(), find_func(), install_func(), is_func(), and main().
int sr_call_count = 0
Definition at line 11 of file sr.c.
Referenced by F_get_labels(), and yyparse().
int sr_no = 0
Definition at line 8 of file sr.c.
Referenced by add_srcode().
code_list_t** srcode = NULL
Definition at line 12 of file sr.c.
Referenced by main().
char** srnames = NULL
Definition at line 13 of file sr.c.
Referenced by find_func(), install_func(), and is_func().