batchgen: stacks.h File Reference
stacks.h File Reference
Functions
void stack_init (void)
void wpush (code_list_t *item)
void spush (code_list_t *item)
code_list_t ** more_whiles (void)
code_list_t ** more_switches (void)
code_list_t * wpop (void)
code_list_t * spop (void)
int inwhile (void)
int inswitch (void)
code_list_t * to_ws (void)
code_list_t * to_ss (void)
char * more_chars (void)
void wawi_push (char item)
char * wawi_pop (void)
char to_wawi_stk (void)
code_list_t * top_cur_stk (void)
Function Documentation
int inswitch (void)
Definition at line 157 of file stacks.c.
References in_switch.
Referenced by yyparse().
int inwhile (void)
Definition at line 152 of file stacks.c.
References in_while.
Referenced by yyparse().
char* more_chars (void)
Definition at line 85 of file stacks.c.
References wawi_stk_sz, and what_are_we_in_stk.
Referenced by stack_init(), and wawi_push().
code_list_t** more_switches (void)
Definition at line 78 of file stacks.c.
References s_stk_sz, and switch_stack.
Referenced by spush(), and stack_init().
code_list_t** more_whiles (void)
Definition at line 71 of file stacks.c.
References w_stk_sz.
Referenced by stack_init(), and wpush().
code_list_t* spop (void)
Definition at line 102 of file stacks.c.
References in_switch, s_stk_ptr, switch_stack, and wawi_pop().
Referenced by yyparse().
void spush (code_list_t * item)
Definition at line 52 of file stacks.c.
References in_switch, more_switches(), s_stk_ptr, s_stk_sz, SWITCH, switch_stack, and wawi_push().
Referenced by stack_init(), and yyparse().
void stack_init (void)
Definition at line 24 of file stacks.c.
References in_switch, in_while, more_chars(), more_switches(), more_whiles(), spush(), switch_stack, wawi_push(), wawi_stk_ptr, what_are_we_in_stk, and wpush().
Referenced by main().
code_list_t* to_ss (void)
Definition at line 127 of file stacks.c.
References s_stk_ptr, and switch_stack.
Referenced by top_cur_stk(), and yyparse().
char to_wawi_stk (void)
Definition at line 134 of file stacks.c.
References wawi_stk_ptr, and what_are_we_in_stk.
Referenced by top_cur_stk().
code_list_t* to_ws (void)
Definition at line 120 of file stacks.c.
References w_stk_ptr.
Referenced by top_cur_stk(), and yyparse().
code_list_t* top_cur_stk (void)
Definition at line 142 of file stacks.c.
References SWITCH, to_ss(), to_wawi_stk(), to_ws(), and WHILE.
Referenced by yyparse().
char* wawi_pop (void)
Definition at line 112 of file stacks.c.
References wawi_stk_ptr, and what_are_we_in_stk.
Referenced by spop(), and wpop().
void wawi_push (char item)
Definition at line 63 of file stacks.c.
References more_chars(), wawi_stk_ptr, wawi_stk_sz, and what_are_we_in_stk.
Referenced by spush(), stack_init(), and wpush().
code_list_t* wpop (void)
Definition at line 92 of file stacks.c.
References in_while, w_stk_ptr, and wawi_pop().
Referenced by yyparse().
void wpush (code_list_t * item)
Definition at line 42 of file stacks.c.
References in_while, more_whiles(), w_stk_ptr, w_stk_sz, wawi_push(), and WHILE.
Referenced by stack_init(), and yyparse().