batchgen: y.tab.c File Reference
y.tab.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <ctype.h>
#include <io.h>
#include <string.h>
#include "batchgen.h"
#include "bkpatch.h"
#include "stacks.h"
#include "sr.h"
Classes
union YYSTYPE
Defines
#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define yyclearin (yychar=(-1))
#define yyerrok (yyerrflag=0)
#define YYRECOVERING (yyerrflag!=0)
#define YYPREFIX "yy"
#define YYSTACKSIZE 5000
#define LEXERROR 257
#define FDEF 258
#define identifier 259
#define func_id 260
#define en_var 261
#define param 262
#define ERRORLEVEL 263
#define GE 264
#define EXIST 265
#define EQ 266
#define NE 267
#define number 268
#define empty 269
#define dos_command 270
#define CASE 271
#define DEFAULT 272
#define IF 273
#define SWITCH 274
#define WHILE 275
#define BREAK 276
#define RETURN 277
#define ELSE 278
#define LOG_OR 279
#define LOG_AND 280
#define YYERRCODE 256
#define YYTABLESIZE 289
#define YYFINAL 13
#define YYMAXTOKEN 280
#define YYMAXDEPTH YYSTACKSIZE
#define yystacksize YYSTACKSIZE
#define YYABORT goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR goto yyerrlab
Functions
int yyerror (char *s)
code_list_t * new_code_node (void)
expr_t * new_expr (void)
char add_string (code_list_t *node, char *string)
char add_text (expr_t *node, char *string)
char concat_text (expr_t *n1, expr_t *n2)
code_list_t * code_join (int n,...)
void emit (code_list_t *c1, FILE *fp)
code_list_t * make_expr_code (char *text, expr_t *expr)
int yyparse ()
Variables
static char yysccsid [] = "@(#)yaccpar 1.9 (Berkeley) 02/21/93"
char * yytext
int lineno = 1
int newlabel = 0
int newcaselabel = 0
int newwhilelabel = 0
int newswitchlabel = 0
int newiflabel = 0
int newcondlabel = 0
int new_sr_return = 0
short yylhs []
short yylen []
short yydefred []
short yydgoto []
short yysindex []
short yyrindex []
short yygindex []
short yytable []
short yycheck []
int yydebug
int yynerrs
int yyerrflag
int yychar
short * yyssp
YYSTYPE * yyvsp
YYSTYPE yyval
YYSTYPE yylval
short yyss [5000]
YYSTYPE yyvs [5000]
Define Documentation
#define BREAK 276
Definition at line 65 of file y.tab.c.
#define CASE 271
Definition at line 60 of file y.tab.c.
#define DEFAULT 272
Definition at line 61 of file y.tab.c.
#define dos_command 270
Definition at line 59 of file y.tab.c.
#define ELSE 278
Definition at line 67 of file y.tab.c.
#define empty 269
Definition at line 58 of file y.tab.c.
#define en_var 261
Definition at line 50 of file y.tab.c.
#define EQ 266
Definition at line 55 of file y.tab.c.
#define ERRORLEVEL 263
Definition at line 52 of file y.tab.c.
#define EXIST 265
Definition at line 54 of file y.tab.c.
#define FDEF 258
Definition at line 47 of file y.tab.c.
#define func_id 260
Definition at line 49 of file y.tab.c.
#define GE 264
Definition at line 53 of file y.tab.c.
#define identifier 259
Definition at line 48 of file y.tab.c.
#define IF 273
Definition at line 62 of file y.tab.c.
#define LEXERROR 257
Definition at line 46 of file y.tab.c.
#define LOG_AND 280
Definition at line 69 of file y.tab.c.
#define LOG_OR 279
Definition at line 68 of file y.tab.c.
#define NE 267
Definition at line 56 of file y.tab.c.
#define number 268
Definition at line 57 of file y.tab.c.
#define param 262
Definition at line 51 of file y.tab.c.
#define RETURN 277
Definition at line 66 of file y.tab.c.
#define SWITCH 274
Definition at line 63 of file y.tab.c.
#define WHILE 275
Definition at line 64 of file y.tab.c.
#define YYABORT goto yyabort
Definition at line 431 of file y.tab.c.
#define YYACCEPT goto yyaccept
Definition at line 433 of file y.tab.c.
#define YYBYACC 1
Definition at line 4 of file y.tab.c.
#define yyclearin (yychar=(-1))
Definition at line 7 of file y.tab.c.
#define YYERRCODE 256
Definition at line 70 of file y.tab.c.
Referenced by yyparse().
#define yyerrok (yyerrflag=0)
Definition at line 8 of file y.tab.c.
#define YYERROR goto yyerrlab
Definition at line 434 of file y.tab.c.
#define YYFINAL 13
Definition at line 194 of file y.tab.c.
Referenced by yyparse().
#define YYMAJOR 1
Definition at line 5 of file y.tab.c.
#define YYMAXDEPTH YYSTACKSIZE
Definition at line 271 of file y.tab.c.
#define YYMAXTOKEN 280
Definition at line 198 of file y.tab.c.
Referenced by yyparse().
#define YYMINOR 9
Definition at line 6 of file y.tab.c.
#define YYPREFIX "yy"
Definition at line 10 of file y.tab.c.
Referenced by yyparse().
#define YYRECOVERING (yyerrflag!=0)
Definition at line 9 of file y.tab.c.
#define YYREJECT goto yyabort
Definition at line 432 of file y.tab.c.
#define yystacksize YYSTACKSIZE
Definition at line 290 of file y.tab.c.
Referenced by yyparse().
#define YYSTACKSIZE 5000
Definition at line 26 of file y.tab.c.
#define YYTABLESIZE 289
Definition at line 131 of file y.tab.c.
Referenced by yyparse().
Function Documentation
char add_string (code_list_t * node, char * string)
Definition at line 309 of file y.tab.c.
References code_list::code.
Referenced by add_srcode(), add_text(), main(), make_expr_code(), and yyparse().
char add_text (expr_t * node, char * string)
Definition at line 319 of file y.tab.c.
References add_string(), expr::expr_code, and new_code_node().
Referenced by concat_text(), make_expr_code(), and yyparse().
code_list_t* code_join (int n, ...)
Definition at line 350 of file y.tab.c.
References code_list::next.
Referenced by add_srcode(), main(), make_expr_code(), and yyparse().
char concat_text (expr_t * n1, expr_t * n2)
Definition at line 329 of file y.tab.c.
References add_text(), code_list::code, expr::expr_code, and TEXTLEN.
Referenced by yyparse().
void emit (code_list_t * c1, FILE * fp)
Definition at line 375 of file y.tab.c.
References code_list::code, and code_list::next.
Referenced by write_code(), and write_optim_code().
code_list_t* make_expr_code (char * text, expr_t * expr)
Definition at line 384 of file y.tab.c.
References add_string(), add_text(), code_join(), expr::expr_code, expr::falselist, makelist(), new_code_node(), and expr::truelist.
Referenced by yyparse().
code_list_t* new_code_node (void)
Definition at line 299 of file y.tab.c.
Referenced by add_srcode(), add_text(), main(), make_expr_code(), and yyparse().
expr_t* new_expr (void)
Definition at line 304 of file y.tab.c.
Referenced by yyparse().
int yyerror (char * s)
Definition at line 293 of file y.tab.c.
Referenced by yyparse().
int yyparse (void)
Definition at line 436 of file y.tab.c.
References add_srcode(), add_string(), add_text(), AND_TRUE_PFX, backpatch_str(), cl, code_list::code, code_join(), YYSTYPE::code_node, concat_text(), ELSE_PFX, END_CASE_PFX, END_LABEL, END_SWITCH_PFX, ENDIF_PFX, ENDWHILE_PFX, expr::expr_code, YYSTYPE::expr_node, expr::falselist, find_func(), code_list::gotos, IF_PFX, in_sr, install_func(), inswitch(), YYSTYPE::integer, inwhile(), is_func(), label_details::label, lineno, make_expr_code(), makelist(), merge(), new_code_node(), new_expr(), newcaselabel, newcondlabel, newiflabel, newlabel, newwhilelabel, code_list::next, OR_FALSE_PFX, spop(), spush(), sr_call_count, to_ss(), to_ws(), top_cur_stk(), expr::truelist, WHILE_BODY_PFX, WHILE_PFX, wpop(), wpush(), yychar, yycheck, yydebug, yydefred, yydgoto, YYERRCODE, yyerrflag, yyerror(), YYFINAL, yygindex, yylen, yylex(), yylhs, YYMAXTOKEN, yynerrs, YYPREFIX, yyrindex, yysindex, yyss, yyssp, yystacksize, yytable, YYTABLESIZE, and yytext.
Referenced by main().
Variable Documentation
int lineno = 1
Definition at line 29 of file y.tab.c.
Referenced by yyparse().
int new_sr_return = 0
Definition at line 36 of file y.tab.c.
int newcaselabel = 0
Definition at line 31 of file y.tab.c.
Referenced by yyparse().
int newcondlabel = 0
Definition at line 35 of file y.tab.c.
Referenced by yyparse().
int newiflabel = 0
Definition at line 34 of file y.tab.c.
Referenced by yyparse().
int newlabel = 0
Definition at line 30 of file y.tab.c.
Referenced by yyparse().
int newswitchlabel = 0
Definition at line 33 of file y.tab.c.
int newwhilelabel = 0
Definition at line 32 of file y.tab.c.
Referenced by yyparse().
int yychar
Definition at line 283 of file y.tab.c.
Referenced by yyparse().
short yycheck[]
Definition at line 163 of file y.tab.c.
Referenced by yyparse().
int yydebug
Definition at line 280 of file y.tab.c.
Referenced by main(), and yyparse().
short yydefred[]
Initial value:
 {                                      0,
   10,    0,   53,    2,    0,    0,    0,    0,   25,    0,
    0,    0,    0,   19,    0,    4,    5,    7,    3,    6,
    9,    8,    0,   11,   44,   46,   48,   50,   52,    0,
    0,    0,    0,    0,   27,   28,    0,   18,    0,   20,
    0,    0,   45,   47,   49,   51,    0,   16,    0,    0,
    0,    0,    0,    0,   34,    0,   32,    0,    0,   29,
   17,   14,    0,   15,    0,    0,    0,    0,    0,    0,
   36,    0,    0,    0,    0,    0,    0,    0,   12,    0,
    0,    0,    0,   35,    0,    0,    0,    0,   33,    0,
    0,    0,    0,   24,   26,   13,   22,
}
Definition at line 87 of file y.tab.c.
Referenced by yyparse().
short yydgoto[]
Initial value:
 {                                      13,
   14,   15,   16,   17,   18,   19,   20,   21,   22,   53,
   54,   55,   56,   57,   23,   42,   92,   77,   34,
}
Definition at line 99 of file y.tab.c.
Referenced by yyparse().
int yyerrflag
Definition at line 282 of file y.tab.c.
Referenced by yyparse().
short yygindex[]
Initial value:
 {                                      0,
  -10,   55,    0,    0,    0,  -22,    0,    0,    0,    3,
   19,    0,   -1,  -32,    0,    0,    0,    0,    0,
}
Definition at line 127 of file y.tab.c.
Referenced by yyparse().
short yylen[]
Initial value:
 {                                         2,
    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
    0,    0,    7,    3,    4,    3,    3,    2,    1,    2,
    5,    7,    0,    6,    0,    6,    2,    2,    3,    1,
    3,    1,    3,    1,    3,    2,    3,    3,    3,    3,
    2,    3,    3,    1,    2,    1,    2,    1,    2,    1,
    2,    1,    1,
}
Definition at line 79 of file y.tab.c.
Referenced by yyparse().
short yylhs[]
Initial value:
 {                                        -1,
    0,    1,    1,    1,    1,    1,    1,    1,    1,    1,
   16,   17,    9,    8,    7,    7,    6,    6,    2,    2,
    3,    3,   18,    3,   19,    4,    5,    5,    5,   10,
   10,   13,   13,   14,   14,   14,   12,   12,   12,   12,
   12,   12,   12,   11,   11,   11,   11,   11,   11,   11,
   11,   11,   15,
}
Definition at line 71 of file y.tab.c.
Referenced by yyparse().
YYSTYPE yylval
Definition at line 287 of file y.tab.c.
int yynerrs
Definition at line 281 of file y.tab.c.
Referenced by yyparse().
short yyrindex[]
Initial value:
 {                                      0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,   65,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,  -24,    0,   25,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,  -41,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,  -39,
  -37,  -35,  -33,    0,  -23,    1,  -31,  -29,    0,    0,
    0,    0,    0,    0,    0,    0,    0,
}
Definition at line 115 of file y.tab.c.
Referenced by yyparse().
char yysccsid[] = "@(#)yaccpar 1.9 (Berkeley) 02/21/93" [static]
Definition at line 2 of file y.tab.c.
short yysindex[]
Initial value:
 {                                    -84,
    0, -246,    0,    0, -234,  -36,  -17,   -8,    0,  -16,
  -56, -114,    0,    0,  -84,    0,    0,    0,    0,    0,
    0,    0,   -4,    0,    0,    0,    0,    0,    0,  -51,
  -84,   20, -234,    2,    0,    0,  -40,    0,  -92,    0,
    8,   15,    0,    0,    0,    0,  -84,    0,  -34, -234,
   20,   20,  -27, -221,    0, -224,    0, -211,   20,    0,
    0,    0,   17,    0, -234, -234, -234, -234, -211,  -26,
    0,   20,  -84, -234, -234,   20,   18,  -25,    0, -211,
 -211, -211, -211,    0, -224, -217, -211, -211,    0,  -84,
  -84,  -59,  -84,    0,    0,    0,    0,
}
Definition at line 103 of file y.tab.c.
Referenced by yyparse().
short yyss[5000]
Definition at line 288 of file y.tab.c.
Referenced by yyparse().
short* yyssp
Definition at line 284 of file y.tab.c.
Referenced by yyparse().
short yytable[]
Definition at line 132 of file y.tab.c.
Referenced by yyparse().
char* yytext
YYSTYPE yyval
Definition at line 286 of file y.tab.c.
YYSTYPE yyvs[5000]
Definition at line 289 of file y.tab.c.
YYSTYPE* yyvsp
Definition at line 285 of file y.tab.c.