@echo off
rem this file has been generated by batchgen and may be overwritten
rem command line: batchgen  eg1.bg
rem date 2016-5-5 18:32:59

@goto main
:main
if "%1" == "%2" goto AT0
goto ORF1
:AT0
if "%3" == "%4" goto ORF1
goto IF0
:ORF1
if exist %5 goto IF0
goto EI0
:IF0
 rem this will be copied verbatim
       @echo it's true 
rem endif
:EI0
:batch_end
