@echo off
rem this file has been generated by batchgen and may be overwritten
rem command line: batchgen -orb vc_make.bc
rem date 2007-7-2 11:21:33
@goto main
:SR2
   echo usage vc_make [options]
   echo options
   echo     -d     include debugging code for lexer and parser
   echo     -h     help
goto %_ret_label%
:SR1
if "%1" == "" goto EW0
if not "%1" == "-d" goto LS1
 set DEBUG=True
goto EI0
:LS1
if not "%1" == "-h" goto LS0
set VC_MAKE_HELP=True
goto EI0
:LS0
set ILLEGAL_OPT=True
:EI0
 shift 
goto SR1
:EW0
goto %_ret_label%
:SR0
    set DEBUG=
    set VC_MAKE_HELP=
    set ILLEGAL_OPT=
    set SOURCE_FILES=
    set LEX_FLAGS=
    set YACC_FLAGS=
    set CC_FLAGS=
    set SOURCE_FILES=batchgen.c bkpatch.c fileread.c lex.yy.c optim.c sr.c stacks.c y.tab.c
    set CC=cl
    set FLEX=flex
    set YACC=yacc
goto %_ret_label%
:main
@echo off
set _ret_label=ESR0
goto SR0
:ESR0
set _ret_label=ESR1
goto SR1
:ESR1
if "%VC_MAKE_HELP%" == "True" goto IF4
if not "%ILLEGAL_OPT%" == "True" goto LS4
:IF4
set _ret_label=ESR2
goto SR2
:ESR2
goto batch_end
:LS4
if not "%DEBUG%" == "" goto LS2
       set LEX_FLAGS=
       set YACC_FLAGS= -vd
       set CC_FLAGS=/nologo /ML /W4 /D "WIN32" /D "NDEBUG" /D "_CONSOLE"
       set YYDEBUG=
goto EI2
:LS2
       set LEX_FLAGS=-d
       set YACC_FLAGS=-vdt
       set CC_FLAGS=/nologo /ML /W4 /D "WIN32" /D "_CONSOLE" /D "YYDEBUG"
       set YYDEBUG=1
:EI2
    @echo on
    %FLEX% %LEX_FLAGS% batcomp.l
    %YACC% %YACC_FLAGS% batcomp.y
    %CC% %CC_FLAGS% %SOURCE_FILES%
    @echo off
    copy y.output ..\doc\y.output
    del *.obj
if not "%DEBUG%" == "" goto LS3
       del y.output
       del lex.yy.c
       del y.tab.c
       del y.tab.h
       copy batcomp.exe ..\bin
goto EI3
:LS3
       copy batcomp.exe ..\bin\batcomp_debug.exe
:EI3
 @echo finished 
:batch_end
