#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "batchgen.h"
#include "stacks.h"
/* #include "sr.h" */
#ifdef FILEOPTIM
#include "foptim.h"
#else
#include "optim.h"
#endif

#pragma warning( disable : 4996 )

char getopts (int argc, char *argv[]);
void set_flag(char *argv);
void make_banner(char *progname, char *fname, char *opts, char banner[BUFSIZ]);
void make_opts(char opts[BUFSIZ]);
int write_code(char *banner, FILE *uoofp);
int write_optim_code(char *banner, char **ca, FILE *oofp);

extern FILE *yyin;
extern int yydebug;

char optflag = 0;
code_list_t *cl = NULL;

char main (int argc, char *argv[])
{
    FILE *oofp = NULL, 
         *uoofp = NULL;
    char result = 0, 
         farg = 0;

    #ifndef FILEOPTIM
       char **ca = NULL;
    #endif

    unlink ("bg.bat");
    unlink ("bgo.bat");
    unlink (TMPFNAM);

    farg = getopts (argc, argv);
    if (farg != 0)
        yyin = fopen (argv [farg], "rt");
    else
        yyin = stdin;

    if (yyin == NULL)
    {
       perror ("cannot open input file");
       return 1;
    }

    stack_init ();
    /* yydebug = 1; */
    if (yyparse () == 0)
    {
        char banner[BUFSIZ];
        char opts[BUFSIZ];
        code_list_t *mainjmp = new_code_node ();

		/*
        int i;
        for (i = 0; i < num_sr; i++)
            cl = code_join (2, srcode [i], cl);
        */

        add_string (mainjmp, "@goto main\n");
        cl = code_join (2, mainjmp, cl);

        make_opts(opts);
        make_banner(argv[0], 
                    farg == 0 ? "stdin":argv[farg],
                    opts,
                    banner);
        write_code(banner, uoofp);
        if (optflag)
            write_optim_code(banner, ca, oofp);
   }
   else
   {
      result = 1;
   }

   if (yyin != NULL && yyin != stdin)
      fclose (yyin);

   return result;
}

char getopts (int argc, char *argv[])
{
   char i;
   char fname = 0;

   for (i = 0; i < argc; i++)
   {
      if (argv [i][0] == '-')
         set_flag(argv[i]);
      else if (fname == 0)
         fname = i;
   }

   return fname;
}

/*
    caller is sending us a string from the cmd line
    that is known to be an option.
    we find out what the option is and set flags
    or issue error messages accordingly.
*/
void set_flag(char *argv)
{
    switch (argv [1])
    {
    case 'o':   
    {
        int j;

        optflag = 1;
        for (j = 2; argv [j] != 0; j++)
        {
            switch (argv [j])
            {
            case 'r': 
                remove_rems = 1;
                break;
            case 'b': 
                remove_blanks = 1;
                break;
            default: 
                fprintf (stderr, 
                         "unknown option -%c\n",\
                         argv [j]);
                break;
            }
        }
        break;
    }
    case 'h':   
        fprintf (stderr, "usage: %s [-o[r|b]] filename\n", argv[0]);
        exit (3);
    default: 
        fprintf (stderr, "unknown option -%c\n", argv [1]);
    break;
    }
}

void make_opts(char opts[BUFSIZ])
{
    opts[0] = 0;
    if (optflag)
        strcpy(opts, "-o");
    if (remove_rems)
        strcat(opts, "r");
    if (remove_blanks)
        strcat(opts, "b");
}

void make_banner(char *progname, char *fname, char *opts, char banner[BUFSIZ])
{
    time_t timeNow;
    char szTime[BUFSIZ];
    struct tm *localTime = NULL;

    time(&timeNow);
    localTime = localtime(&timeNow);
    sprintf (szTime, 
             "%d-%d-%d %02d:%02d:%02d", 
             localTime->tm_year + 1900,
             localTime->tm_mon,
             localTime->tm_mday+1, /* yes, really. days start at 1, 
                                      months start at 0 */
             localTime->tm_hour,
             localTime->tm_min,
             localTime->tm_sec);

    banner[0] = 0;
    sprintf(banner,
          "@echo off\n"
          "rem this file has been generated by batchgen and may be overwritten\n"
          "rem command line: %s %s %s\n"
          "rem date %s\n\n",
          progname,
          opts,
          fname,
          szTime);
}

int write_code(char *banner, FILE *uoofp)
{
    uoofp = fopen ("bg.bat", "wt");
    if (uoofp == NULL)
    {
        fprintf (stderr, "unable to open unopt out file\n");
        return 1;
    }

    fprintf(uoofp, "%s", banner);
    emit (cl, uoofp);
    fclose (uoofp);

    return 0;
}

int write_optim_code(char *banner, char **ca, FILE *oofp)
{
    #ifdef FILEOPTIM
    oofp = fopen ("bgo.bat", "wt");
    if (oofp == NULL)
    {
        fprintf (stderr, "unable to open opt out file\n");
        return 1;
    }
    emit (cl, oofp);
    if (fclose (oofp) != 0)
        perror ("oofp");

    if (F_optimize () != 0)
    {
        fprintf (stderr, "optimize failed\n");
        if (system ("copy bco.bat bco.tmp > nul") != 0)
            perror ("opt fail");
        if (system ("echo rem BAD FILE > bco.bat") != 0)
            perror ("opt fail");
        if (system ("echo goto "DUD_FILE_LABEL" >> bco.bat") != 0)
            perror ("opt fail");
        if (system ("type bco.tmp >> bco.bat") != 0)
            perror ("opt fail");
        if (system ("echo:"DUD_FILE_LABEL">>bco.bat") != 0)
            perror ("opt fail");
    }
    #else
    oofp = fopen ("bgo.bat", "wt");
    if (oofp == NULL)
    {
        fprintf (stderr, "unable to open opt out file\n");
        return 1;
    }

    ca = copy_lines (cl);  
    if (optimize (ca) == 0)
    {
        fprintf(oofp, "%s", banner);
        print_ca (ca, oofp);
    }
    else
    {
        fprintf (stderr, "optimize failed\n");
        fprintf (oofp, "rem BAD FILE\ngoto "DUD_FILE_LABEL"\n");
        print_ca (ca, oofp);
        fprintf (oofp, ":"DUD_FILE_LABEL"\n");
    }
    fclose (oofp);
    #endif

    return 0;
}

