@echo off
rem this file has been generated by batchgen and may be overwritten
rem command line: I:\usr\NIK\dev\batchgen\vce2010\Debug\batchgen.exe -orb I:\usr\NIK\dev\batchgen\bin\getTiffs.bg
rem date 2012-2-9 21:30:45

@goto main
rem sub routine
:copyTiffs

    rem copyTiffs (pic, dest)

if exist %TIFF_LOC%\%1.tif goto IF4
goto LS4
:IF4

        copy %TIFF_LOC%\%1.tif %2
    

goto EI4
rem else
:LS4
if exist %TIFF_LOC%\2009-08-16_to_2010-08-10\%1.tif goto IF3
goto LS3
:IF3

        copy %TIFF_LOC%\2009-08-16_to_2010-08-10\%1.tif %2
    

goto EI3
rem else
:LS3
if exist %TIFF_LOC%\2010-08-14_to_2011-03-10\%1.tif goto IF2
goto LS2
:IF2

        copy %TIFF_LOC%\2010-08-14_to_2011-03-10\%1.tif %2
    

goto EI2
rem else
:LS2
if exist %TIFF_LOC%\2011-03-11_to_2011-04-22\%1.tif goto IF1
goto LS1
:IF1

        copy %TIFF_LOC%\2011-03-11_to_2011-04-22\%1.tif %2
    

goto EI1
rem else
:LS1
if exist %TIFF_LOC%\2011-04-24_to_2011-10-30\%1.tif goto IF0
goto EI0
:IF0

        copy %TIFF_LOC%\2011-04-24_to_2011-10-30\%1.tif %2
    
rem endif
:EI0
rem endif
:EI1
rem endif
:EI2
rem endif
:EI3
rem endif
:EI4
rem end sub routine
goto :eof

rem sub routine
:usage

echo usage %0 picListFile and destinationDirectory
echo this script will copy tiff files listed in
echo the pic list from \_large\photos\photoNJ\tiffs
echo to the specified directory

rem end sub routine
goto :eof

rem sub routine
:argError

usage()

rem end sub routine
goto :eof

rem sub routine
:noPicList

    rem noPicList (filename)
    echo can't find %1, exiting

rem end sub routine
goto :eof

:main

set TIFF_LOC=%LA_CIE_DRIVE%:\_large\photos\photoNJ\tiffs

if "%1" == "" goto EI5
goto IF5
:IF5
call :argError
 goto end 
rem endif
:EI5
if exist picList.txt goto EI6
goto IF6
:IF6
     
    call :noPicList picList.txt
    goto end

rem endif
:EI6

for /f %%t in (picList.txt) do call :copyTiffs %%t .
:end
set TIFF_LOC=

:batch_end
