@echo off
rem this file has been generated by batchgen and may be overwritten
rem command line: I:\usr\NIK\dev\batchgen\vce2010\Debug\batchgen.exe -orb I:\usr\NIK\dev\batchgen\bin\getTiffs.bg
rem date 2012-2-9 21:30:45

@goto main
:copyTiffs
if not exist %TIFF_LOC%\%1.tif goto LS4
        copy %TIFF_LOC%\%1.tif %2
goto EI0
:LS4
if not exist %TIFF_LOC%\2009-08-16_to_2010-08-10\%1.tif goto LS3
        copy %TIFF_LOC%\2009-08-16_to_2010-08-10\%1.tif %2
goto EI0
:LS3
if not exist %TIFF_LOC%\2010-08-14_to_2011-03-10\%1.tif goto LS2
        copy %TIFF_LOC%\2010-08-14_to_2011-03-10\%1.tif %2
goto EI0
:LS2
if not exist %TIFF_LOC%\2011-03-11_to_2011-04-22\%1.tif goto LS1
        copy %TIFF_LOC%\2011-03-11_to_2011-04-22\%1.tif %2
goto EI0
:LS1
if exist %TIFF_LOC%\2011-04-24_to_2011-10-30\%1.tif         copy %TIFF_LOC%\2011-04-24_to_2011-10-30\%1.tif %2
:EI0
goto :eof
:argError
usage()
goto :eof
:noPicList
    echo can't find %1, exiting
goto :eof
:main
set TIFF_LOC=%LA_CIE_DRIVE%:\_large\photos\photoNJ\tiffs
if "%1" == "" goto EI5
call :argError
 goto end 
:EI5
if exist picList.txt goto EI6
    call :noPicList picList.txt
    goto end
:EI6
for /f %%t in (picList.txt) do call :copyTiffs %%t .
:end
set TIFF_LOC=
